package ai.cuebook.thehelicoptergame.enums;

public enum Actions {
    START_FIRST_ROUND_OFFENCE,START_SECOND_ROUND_DEFENCE,
    START_FIRST_ROUND_DEFENCE,START_SECOND_ROUND_OFFENCE,
    START_HELICOPTER, DROP_BOMB_PERSONEL,DRIVE_FAST,GO_DOWN,
    ROTATE_LEFT,ROTATE_RIGHT,SHOOT_HELICOPTER,SHOOT_BOMB_PERSONEL
}
