package ai.cuebook.thehelicoptergame.enums;

public enum RedisKeys {
    HELICOPTER_Y,
    HELICOPTER_X,
    TOTAL_HELICOPTERS,
    HELICOPTER,HELICOPTER_SPEED,
    HELICOPTER_PREVIOUS_ACTION_TIME,
    HELICOPTER_BOMB_PERSONNEL,

    GUN_ANGLE,

    GROUND_SOLDIER_DROP_POSITION,
    GROUND_SOLDIER_DROP_TIME
}
